### ISSUE TITLE
meteorhelper not activating when meteor project is in a sub-directory

### ISSUE THREAD

**Issue by hluz** [ramonitor/vscode-meteorhelper#3]
Trying to set up VSCode with meteorhelper, but I can't get meteorhelper to activate when the meteor project is in a sub-dir of the VSCode workspace dir. It works otherwise (meteor project is at the root of the VSCode workspace). I have the workspace settings file setup with `"meteorhelper.relativeProjectPath": "meteorProjDir"`.
(using MacOS VSCode v1.12.2)

**Comment by ramonitor** [comment]
Unfortunately AFAIK its not possible to automatically activate VSCode extensions via the `workspaceContains` 
event based on a folder structure below the current root directory. That's why the extension is not automatically activated as opposed to the Meteor project folder being in the root of the workspace.  

See: [https://code.visualstudio.com/docs/extensionAPI/activation-events](https://code.visualstudio.com/docs/extensionAPI/activation-events) for more information.
